fos_rest:
    view:
        view_response_listener:  true

    exception:
        messages:
            Symfony\Component\HttpKernel\Exception\HttpException: true
    #    exception_controller: 'fos_rest.exception.controller:showAction'

    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type:  true
        decoders:
            json: fos_rest.decoder.json

    body_converter:
        enabled: true
        validate: true
